complete -c rnm -s d -l dry-run -d 'Show planned renames'
complete -c rnm -l disable-log -d 'Disable file logging'
complete -c rnm -l rollback -d 'Execute the latest rollback script'
complete -c rnm -l camel-case -d 'Use camelCase'
complete -c rnm -l pascal-case -d 'Use PascalCase'
complete -c rnm -l snake-case -d 'Use snake_case'
complete -c rnm -l screaming-snake-case -d 'Use SCREAMING_SNAKE_CASE'
complete -c rnm -l kebab-case -d 'Use kebab-case'
complete -c rnm -l install-completions -xa 'bash fish zsh nu all detect' -d 'Select completions to install or update'
complete -c rnm -s c -l gen-config -d 'Generate default config'
complete -c rnm -s i -l install -d 'Install binary, man page, detected completions'
complete -c rnm -s r -l reinstall -d 'Reinstall binary, man page, selected completions'
complete -c rnm -s u -l update -d 'Update changed binary, man page, selected completions'
complete -c rnm -s x -l uninstall -d 'Remove binary, man page, completions'
complete -c rnm -s p -l purge -d 'Remove binary, man page, completions, and config'
complete -c rnm -s h -l help -d 'Show manual page'
complete -c rnm -a "(__fish_complete_directories)" -d 'Target directory'
